#ifndef PARAMS_H
#define PARAMS_H

#define PORT 80
#define LINE_BUFFER_SIZE 4096
#define MAXADDRLEN 128
#define MAXPATHLEN 512
#define MAX_HTTP_HEADER_NAME_LEN 2048
#define MAX_HTTP_HEADER_VALUE_LEN 2048
#define MAX_HTTP_HEADERS 100

#endif
